services:
  neo4j:
    image: neo4j:5.25.1
    container_name: neo4j-container
    volumes:
      - ./neo4j/data:/var/lib/neo4j/data
      - ./neo4j/import:/var/lib/neo4j/import
      - ./docker:/docker
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_server_http_advertised__address: localhost
      NEO4J_server_memory_pagecache_size: 2G
      NEO4J_dbms_memory_transaction_total_max: 4G
      NEO4J_initial_dbms_default__database: courseProject2024.db
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: 'apoc.*'
      NEO4J_dbms_security_procedures_allowlist: 'apoc.*'
      EXTENSION_SCRIPT: /docker/neo4j-init.sh
    ports:
      - "7474:7474"
      - "7687:7687"
