PREFIX data: <http://localhost/sancho/resource/>
PREFIX vocab: <http://localhost/sancho/vocab/>

SELECT ?movie ?title
WHERE {
  ?actor vocab:name "Buster Keaton" ;
         vocab:actedIn ?movie .
  ?movie vocab:title ?title .
}
