PREFIX data: <http://localhost/sancho/resource/>
PREFIX vocab: <http://localhost/sancho/vocab/>

SELECT ?movie ?title ?imdbRating
WHERE {
    ?movie vocab:title ?title ;
        vocab:imdbRating ?imdbRating .
}
ORDER BY DESC(?imdbRating)
LIMIT 10
